INSERT INTO roles (name)
SELECT 'ROLE_PLATFORM_ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_PLATFORM_ADMIN');

INSERT INTO roles (name)
SELECT 'ROLE_MERCHANT_OPERATOR'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_MERCHANT_OPERATOR');

INSERT INTO roles (name)
SELECT 'ROLE_REGULAR_BUYER'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_REGULAR_BUYER');

INSERT INTO roles (name)
SELECT 'ROLE_REVIEWER'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_REVIEWER');

INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM users u
JOIN roles r ON r.name = 'ROLE_PLATFORM_ADMIN'
WHERE u.username = 'admin'
  AND NOT EXISTS (
      SELECT 1
      FROM user_roles ur
      WHERE ur.user_id = u.id AND ur.role_id = r.id
  );
